Update gh pages 20181213
RobotLocomotion/styleguide pull request #16
Opened 2018-12-13 14:37 UTC by EricCousineau-TRI

Merge remote-tracking branch 'google/gh-pages' (6271f3f) into update-gh-pages-20181213

2018-12-13 14:40 UTC, EricCousineau-TRI reviewed
+@jwnimmer-tri and +@soonho-tri for initial review, please.

I did a brief merge, and will myself go over more of the added text to scan it. I am ignoring the `py_guide.md` updates. I want to make sure I push the PR though, so I don't let it bitrot like #9...

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTc-R3i4B1PBeJnhiYR:bphxmub)* status: 1 unresolved discussion, platform LGTM missing

___
*[cppguide.html, line 996 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc-Id32iMxOdJXyif6:-LTc-Id32iMxOdJXyif7:b4zdi6t) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L996)):*
> ```HTML
> <code>static T&amp; t = *new T;</code> is allowed.</p>
> 
> <span class="drake">
> ```

Let me know if this should remain in the summary.


<!-- Sent from Reviewable.io -->

2018-12-13 15:33 UTC, soonho-tri requested changes
Checkpoint.

 - Still reading `cppguide.html`. I assume that I don't need to review the changes in the other languages (e.g. objc, java, python). Please let me know if I'm wrong.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTcBafw-phUZGdpEq56:b-xz5rv3)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc5-FB5pYDEs8qiQlk:-LTc5-FCAHdBGkk15UB1:b-vlopyt) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L177)):*
> ```HTML
> 
> <p>
> Currently, code should target C++11, i.e., should not use C++14 or
> ```

We need to mention that we allow developers to use C++14 features as we use `--std=c++14`.


<!-- Sent from Reviewable.io -->

2018-12-13 17:18 UTC, jwnimmer-tri commented
A formatted preview is available [here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/EricCousineau-TRI/styleguide/update-gh-pages-20181213/cppguide.html).

2018-12-13 17:26 UTC, jwnimmer-tri commented
___
*[cppguide.html, line 1482 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc_Wu-7ZTTDsL22pyQ:-LTc_Wu-7ZTTDsL22pyR:b3hbuom) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1482)):*
> ```HTML
> </div>
> 
> <div class="decision">
> ```

This paragraph and the next few talk about how we advise developers to add or remove copy/assign/etc.   Given how much they have grown now in the newest upstream, I feel like they might be too misleading now?  I thinktThey should be clarified to note the Drake way.

My guess is that the drake note that we placed atop this section (refering to drake_copyable) should move _here_ instead.

Something like for the below paragraph:
""
Every class's public interface should make explicit which copy and move
operations the class supports.  **A class should use drake_copyable.h macros (...) whenever possible.  Failing that,** it should usually take the form of explicitly declaring and/or deleting the appropriate operations in the ...
""

or something.


<!-- Sent from Reviewable.io -->

2018-12-13 17:26 UTC, jwnimmer-tri commented
___
*[cppguide.html, line 1402 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc_Ac34wm1d-zCwJWS:-LTc_Ac34wm1d-zCwJWT:b61e5nc) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1402)):*
> ```HTML
> macros (either <code>DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN</code> or
> <code>DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN</code>) whenever practical.
> When using the macros, the copy constructor and copy-assignment operator at
> ```

nit We lost a "not" here during the merge.


<!-- Sent from Reviewable.io -->

2018-12-13 17:33 UTC, jwnimmer-tri commented
___
*[cppguide.html, line 3527 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcc8ozBSvPAR8M3Inn:-LTcc8ozBSvPAR8M3Ino:brjy2wr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L3527)):*
> ```HTML
>   for your particular case, try to avoid or even upgrade APIs that rely on the
>   <code>printf</code> family. Instead use a library supporting typesafe numeric
>   formatting, such as
> ```

Should we mention `fmt` as first on the list here, because it's what Drake uses (and is soon to be standardized into `std::`)?


<!-- Sent from Reviewable.io -->

2018-12-13 17:38 UTC, jwnimmer-tri commented
___
*[cppguide.html, line 5049 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcdFlP4Oo1KT3PckAb:-LTcdFlP4Oo1KT3PckAc:b-wj6wg7) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L5049)):*
> ```HTML
> <p>If you make significant changes to a file with an
> author line, consider deleting the author line.
> New files should usually not contain copyright notice or
> ```

This is contrary to the "Authorship Comments" section we've added.  We should strikethrough the author stuff (but not copyright stuff) here, with a link to our custom section.


<!-- Sent from Reviewable.io -->

2018-12-13 17:47 UTC, jwnimmer-tri requested changes
First pass complete.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTcfRlJ95vXQpmGkU1b:bvb1a6z)* status: 9 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 996 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc-Id32iMxOdJXyif6:-LTceK0QCzLuA33dINxz:b-4lerox) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L996)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Let me know if this should remain in the summary.
</blockquote></details>

I think it's useful to keep.
___
*[cppguide.html, line 998 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTceMAKALiLvFWmYt66:-LTceMAL8XFJVfqY_PRg:b-ssgq82) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L998)):*
> ```HTML
> <span class="drake">
> <p>Types wrapped within
> <a href="http://drake.mit.edu/doxygen_cxx/classdrake_1_1never__destroyed.html">drake::never_destroyed&lt;T&gt;</a>.
> ```

nit This has a stray `.` at the end, even though the sentence continues.
___
*[cppguide.html, line 1028 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTceks90DpaUpd84BOK:-LTceks90DpaUpd84BOL:b-92do7c) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1028)):*
> ```HTML
> 
> <p>Constant initialization is always allowed. Constant initialization of
> static storage duration variables should be marked with <code>constexpr</code>
> ```

To the whole team -- I think this is a good idea, but perhaps makes our code insta-buggy since we haven't been doing it so far.  Are we okay with this change now?
___
*[cppguide.html, line 1092 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcfHwWAw2oAUe294nn:-LTcfHwX7UpnxqMZHKx4:bdnsbkj) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1092)):*
> ```HTML
>     <code>static const auto* const impl = new T(args...);</code> (If the
>     initialization is more complex, it can be moved into a function or lambda
>     expression.)</li>
> ```

This final bullet should advise to use never_destroyed, instead of a bare pointer.


<!-- Sent from Reviewable.io -->

2018-12-13 18:55 UTC, soonho-tri requested changes
First pass complete.

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTcvAwu65e5ohcYNXst:b-nxgzn5)* status: 12 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 1032 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcC1N-8fx9opotL3TX:-LTcC1N-8fx9opotL3TY:bqktar0) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1032)):*
> ```HTML
> 
> <a href="https://github.com/abseil/abseil-cpp/blob/03c1513538584f4a04d666be5eb469e3979febba/absl/base/attributes.h#L540">
> <code>ABSL_CONST_INIT</code></a>
> ```

Abseil is mentioned throughout this document, we need to either 1) bring abseil into our codebase and allow users to use it, or 2) not mention it in this guide.
___
*[cppguide.html, line 2034 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcpbLeCVLbou9myvpw:-LTcpbLeCVLbou9myvpx:b-2wvo5u) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L2034)):*
> ```HTML
> string&amp;</code> and overload it with another that
> takes <code>const char*</code>. However, in this case consider
> std::string_view
> ```

`std::string_view` is only available in c++17
___
*[cppguide.html, line 3125 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTctMA68_nk9UlUVBaF:-LTctMA68_nk9UlUVBaG:bfsn96d) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L3125)):*
> ```HTML
> In particular,
> 
> logging libraries are usually a better
> ```

worth mentioning `DRAKE_SPDLOG_*` macros in `common/text_logging.h`?


<!-- Sent from Reviewable.io -->

2018-12-13 19:00 UTC, jwnimmer-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 12 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 1032 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcC1N-8fx9opotL3TX:-LTcvWrB2zUpYi11kE8f:bnhbhm6) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1032)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Abseil is mentioned throughout this document, we need to either 1) bring abseil into our codebase and allow users to use it, or 2) not mention it in this guide.
</blockquote></details>

Keeping large diffs is painful.  Instead of culling mentions of Abseil entirely or adding strikethroughs, we could instead add a clarificiation atop the document that Abseil is not used in Drake.
___
*[cppguide.html, line 2034 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcpbLeCVLbou9myvpw:-LTcvxib2tPbfTs1CKXi:beduyfk) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L2034)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

`std::string_view` is only available in c++17
</blockquote></details>

I think this mention is harmless.  The "definition" sections are illustrative, not prescriptive.


<!-- Sent from Reviewable.io -->

2018-12-13 19:04 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 11 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 1032 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcC1N-8fx9opotL3TX:-LTcwzMU7RWDGm6l0BIR:bwh0yib) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1032)):*
> add a clarificiation atop the document that Abseil is not used in Drake.

 I like the idea.


<!-- Sent from Reviewable.io -->

2018-12-13 20:01 UTC, sherm1 approved these changes
I looked through the cppguide. I see a lot of Abseil references now. We could either remove them or decide to adopt Abseil to go with the flow. I'm guessing that there will be a growing amount of Abseil in future updates.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTd8wnPC-4JPZ40kLsQ:b-rvxp7b)* status: 13 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 513 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcqysiEH6_IW15bat8:-LTcqysjDJJkKjTvXetu:b-c26gqg) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L513)):*
> ```HTML
> are essentially interchangeable with their C++ counterparts
> (<code>cstddef</code>)
> Either style is acceptable, but prefer consistency with existing code.</p>
> ```

BTW I'd prefer that we stick with `<cstddef>` throughout Drake.
___
*[cppguide.html, line 907 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcrXP3ErRRo_5fSbdu:-LTcrXP3ErRRo_5fSbdv:brsste0) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L907)):*
> ```HTML
> Use of dynamic initialization for static class member variables or variables at
> namespace scope is discouraged, but allowed in limited circumstances; see below
> for details.</p>
> ```

minor: needs a reference to our never_destroyed utility.
___
*[cppguide.html, line 1028 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTceks90DpaUpd84BOK:-LTcsdPkAfhYioqjmmS4:b-ev4sbq) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1028)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To the whole team -- I think this is a good idea, but perhaps makes our code insta-buggy since we haven't been doing it so far.  Are we okay with this change now?
</blockquote></details>

I'm happy with this change now. We can apply it to new code and eventually retrofit old code.
___
*[cppguide.html, line 1108 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTctOxLBE2wiqLSTzyz:-LTctOxLBE2wiqLSTzz-:b-dvkj9h) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1108)):*
> ```HTML
> attribute. Prefer
> <code>thread_local</code> over other ways of defining thread-local data.</p>
> </div>
> ```

minor: this doesn't seem applicable to us due to lack of abseil.
___
*[cppguide.html, line 1186 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTctxbTBA78STE-WsgY:-LTctxbTBA78STE-WsgZ:bjkur41) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1186)):*
> ```HTML
>     (or <code>constexpr</code>, but that should be rare):</p>
> 
> <pre>ABSL_CONST_INIT thread_local Foo foo = ...;
> ```

BTW more abseil
___
*[cppguide.html, line 1395 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcuJm9AFVThiXZTloK:-LTcuJm9AFVThiXZTloL:b-izarjr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1395)):*
> ```HTML
> <div class="summary">
> <p>A class's public API should make explicit whether the class is copyable,
> move-only, or neither copyable nor movable. Support copying and/or
> ```

BTW (we are missing a nice move-only macro)
___
*[cppguide.html, line 1557 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcv2_v7JjI-OCHi14J:-LTcv2_v7JjI-OCHi14K:bt86r2t) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1557)):*
> ```HTML
> copyable, provide a public virtual <code>Clone()</code>
> method, and a protected copy constructor that derived classes
> can use to implement it.</p>
> ```

BTW Yay! That's my favorite way to do it.
___
*[cppguide.html, line 3452 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTd7PDSB4EZkXx357IR:-LTd7PDT1uYow5QORMp-:b-2ctpvb) ([raw file](https://github.com/robotlocomotion/styleguide/blob/fa8a90e41994515caad2cd56bed93b4126db7872/cppguide.html#L3452)):*
> ```HTML
> 
> <p>Use <code>0</code> for integers and <code>0.0</code>
> for reals. This is not controversial.</p>
> ```

BTW :smile:  I guess someone objected!
___
*[cppguide.html, line 3527 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcc8ozBSvPAR8M3Inn:-LTd6uQVDIRvbD_zlVmA:bb77ufg) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L3527)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Should we mention `fmt` as first on the list here, because it's what Drake uses (and is soon to be standardized into `std::`)?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2018-12-15 14:04 UTC, jwnimmer-tri commented
___
*[cppguide.html, line 907 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcrXP3ErRRo_5fSbdu:-LTm9rTt0TLceVVt1aGt:b-qleshk) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L907)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

minor: needs a reference to our never_destroyed utility.
</blockquote></details>

OK I don't think never_destroyed needs to appear in the "Summary" section here.  There is already a reference to it shortly below, noting that it _is_ trivially destructible.  And then I've already posted a comment many lines down, that we should mention never_destroyed in the "Common patterns" section.  Given the improvements to the overall text here from upstream, I think that's good enough -- the upstream advice is much more on point now.  I think never_destroyed as a last resort (as noted in "Common patterns") is good enough.


<!-- Sent from Reviewable.io -->

2018-12-15 14:07 UTC, jwnimmer-tri reviewed
There was a discussion below about Abseil.  I proposed and Soonho concurred that for now, we should just post a note at the top of this document (in the Drake intro, presumably) that Drake does _not_ have Abseil available, so readers should discount any advice which either suggests or demands that Abseil be used.  We don't want to have to go and edit a strikethrough onto all of mentions of Abseil, because that will just lead to merge hell as upstream continues to evolve.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTmAi9UADz8HVyGMcyF:bfew1ts)* status: 10 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing



<!-- Sent from Reviewable.io -->

2018-12-15 16:26 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 177 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc5-FB5pYDEs8qiQlk:-LTmfV_M50JEd9auUvjm:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L177)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

We need to mention that we allow developers to use C++14 features as we use `--std=c++14`.
</blockquote></details>

Done.
___
*[cppguide.html, line 996 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc-Id32iMxOdJXyif6:-LTmfXM6-zMKIZ5gcB4w:b68elfy) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L996)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think it's useful to keep.
</blockquote></details>

OK Moved it down to just be in the "Common patterns" section.
___
*[cppguide.html, line 1028 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTceks90DpaUpd84BOK:-LTmfbvA5Lrn-1C5KIpS:bzi0m7h) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1028)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I'm happy with this change now. We can apply it to new code and eventually retrofit old code.
</blockquote></details>

Fine by me too!
___
*[cppguide.html, line 1032 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcC1N-8fx9opotL3TX:-LTmff3iDZQxUm7woWww:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1032)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

> add a clarificiation atop the document that Abseil is not used in Drake.

 I like the idea.
</blockquote></details>

Done.
___
*[cppguide.html, line 1092 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcfHwWAw2oAUe294nn:-LTmfgeP4gVj3vePiSgR:b-svewkv) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1092)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This final bullet should advise to use never_destroyed, instead of a bare pointer.
</blockquote></details>

Done. (Struck out last bullet, put the Drake stuff above it.)
___
*[cppguide.html, line 1482 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTc_Wu-7ZTTDsL22pyQ:-LTmfnx6-gdaJYnup3Ba:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1482)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This paragraph and the next few talk about how we advise developers to add or remove copy/assign/etc.   Given how much they have grown now in the newest upstream, I feel like they might be too misleading now?  I thinktThey should be clarified to note the Drake way.

My guess is that the drake note that we placed atop this section (refering to drake_copyable) should move _here_ instead.

Something like for the below paragraph:
""
Every class's public interface should make explicit which copy and move
operations the class supports.  **A class should use drake_copyable.h macros (...) whenever possible.  Failing that,** it should usually take the form of explicitly declaring and/or deleting the appropriate operations in the ...
""

or something.
</blockquote></details>

Done.
___
*[cppguide.html, line 3125 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTctMA68_nk9UlUVBaF:-LTmfpV4BYDqMH4rZKEw:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L3125)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

worth mentioning `DRAKE_SPDLOG_*` macros in `common/text_logging.h`?
</blockquote></details>

Done.
___
*[cppguide.html, line 5049 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcdFlP4Oo1KT3PckAb:-LTmfr_R82RJe-B3-77L:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L5049)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is contrary to the "Authorship Comments" section we've added.  We should strikethrough the author stuff (but not copyright stuff) here, with a link to our custom section.
</blockquote></details>

Done.
___
*[include/styleguide.css, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTmfsg6Ci3cnLQu42i7:-LTmfsg6Ci3cnLQu42i8:b-rcqf0f) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/include/styleguide.css#L62)):*
> ```CSS
> code, samp, var, pre {
>   /* Use effective color from GitHub. */
>   background-color:#F3F3F3;
> ```

FYI I was annoyed at how light the code cells were, made it hard for me to parse `<code/>` elements. GitHub's style use an `alpha` value (yuck!), so I just took a screenshot and got the hex from sampling the color.


<!-- Sent from Reviewable.io -->

2018-12-15 16:27 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 5 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing

___
*[cppguide.html, line 3829 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTmgI15778Ejh-2kT2Z:-LTmgI15778Ejh-2kT2_:b-417mxx) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/cppguide.html#L3829)):*
> ```HTML
> </ul>
> 
> <p class="drake">Note that <code>auto</code> implies <i>value type</i>
> ```

FYI Seems like most people know the `auto&` / `const auto&` bit, but wanted to add this in.


<!-- Sent from Reviewable.io -->

2018-12-15 17:06 UTC, soonho-tri approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing



<!-- Sent from Reviewable.io -->

2018-12-15 19:17 UTC, sherm1 approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing, commit history needs curation



<!-- Sent from Reviewable.io -->

2018-12-15 19:17 UTC, sherm1 approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee soonho-tri, platform LGTM missing, commit history needs curation



<!-- Sent from Reviewable.io -->

2018-12-17 15:29 UTC, jwnimmer-tri commented
___
*[cppguide.html, line 3829 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTmgI15778Ejh-2kT2Z:-LTwlQ-34JBerrad1Zm-:b-1hjd1j) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/cppguide.html#L3829)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI Seems like most people know the `auto&` / `const auto&` bit, but wanted to add this in.
</blockquote></details>

Above, the guide already says "Programmers have to understand the difference between auto and const auto& or they'll get copies when they didn't mean to."  I'm not sure I want to have Drake start to add C++ 101 tutorials to this guide, especially ones that don't have good examples, don't explain it clearly, and don't even bother to link to resources on the topic.  In any case, this kind of change is totally inappropriate for an already-huge "merge with upstream" PR.


<!-- Sent from Reviewable.io -->

2018-12-17 15:46 UTC, jwnimmer-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTwq2XSBY61MRnIsRuY:bnfp4nl)* status: 4 unresolved discussions, LGTM missing from assignee soonho-tri, platform LGTM from [jwnimmer-tri], commit history needs curation

___
*[cppguide.html, line 193 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTwp2dN78gJHTnKHpnf:-LTwp2dN78gJHTnKHpng:b-msw3t4) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/cppguide.html#L193)):*
> ```HTML
> Drake does not use <a href="https://github.com/abseil/abseil-cpp">Abseil</a>;
> please ignore any suggestions or rules that regard Abseil.
> </p>
> ```

This seems a bit buried.  Wouldn't it make more sense at the _very_ top in "Background", e.g., near "Many references to Google are deliberately left in to minimize merge conflicts.".
___
*[cppguide.html, line 1517 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTwoCWc3gSG8rV2T-GY:-LTwoCWd1RtrYOJ5Vj5s:bwxs40u) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/cppguide.html#L1517)):*
> ```HTML
> };
> 
> class NotCopyableOrMovable {
> ```

nit This illustration should use our DRAKE_NO_COPY... macro.  There would be no reason to write the longhand form in Drake.
___
*[cppguide.html, line 1547 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTwoWJN3MkVAbdaI9d4:-LTwoWJN3MkVAbdaI9d5:blwu3nf) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/cppguide.html#L1547)):*
> ```HTML
> costs. Move operations for copyable types are strictly a performance
> optimization and are a potential source of bugs and complexity, so
> avoid defining them unless they are significantly more efficient than
> ```

nit The advice "avoid defining [move operators]" seems contrary to our common practice.  I think it's more correct to say "Avoid _explicitly_ defining them", perhaps?


<!-- Sent from Reviewable.io -->

2018-12-17 16:00 UTC, soonho-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTwtBDe9QbhltKKZlJ8:bnfp4nl)* status: 4 unresolved discussions, platform LGTM from [jwnimmer-tri, soonho-tri], commit history needs curation



<!-- Sent from Reviewable.io -->

2018-12-17 16:42 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri, soonho-tri], commit history needs curation

___
*[cppguide.html, line 193 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTwp2dN78gJHTnKHpnf:-LTx2-4M2BwXceIS-K5X:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/cppguide.html#L193)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This seems a bit buried.  Wouldn't it make more sense at the _very_ top in "Background", e.g., near "Many references to Google are deliberately left in to minimize merge conflicts.".
</blockquote></details>

Done.
___
*[cppguide.html, line 3829 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTmgI15778Ejh-2kT2Z:-LTx23aD-SVrkXGXjIRF:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a11a6b23a889b94c423d0adc45500bb07f4e5c42/cppguide.html#L3829)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Above, the guide already says "Programmers have to understand the difference between auto and const auto& or they'll get copies when they didn't mean to."  I'm not sure I want to have Drake start to add C++ 101 tutorials to this guide, especially ones that don't have good examples, don't explain it clearly, and don't even bother to link to resources on the topic.  In any case, this kind of change is totally inappropriate for an already-huge "merge with upstream" PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-17 16:50 UTC, EricCousineau-TRI reviewed
Platform reviewer bat signal!
+@sherm1 +@ggould-tri +@sammy-tri +@seancurtis-tri +@russtedrake for review, please.

I would prefer to keep the addressed comments as a separate (singular) commit, so will remove "curate commits" the label (also since we now have everyone assigned)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTx2V6M-OjeHzyIDznd:btsu9ln)* status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri, soonho-tri], commit history needs curation

___
*[cppguide.html, line 1395 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTcuJm9AFVThiXZTloK:-LTx34fD1MpGhht_7X_D:b-qfqs55) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3134a66b8f1d26eece576e18676843fc47e63079/cppguide.html#L1395)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW (we are missing a nice move-only macro)
</blockquote></details>

OK Indeed! But it does seem like it may open up to excessive combos, like `NO_COPY_YES_MOVE_NO_ASSIGN` and `NO_COPY_YES_MOVE_YES_ASSIGN` or something like that. I'm fine with things as-is (manual spelling) unless we can think of a simple nice spelling.
___
*[cppguide.html, line 3452 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTd7PDSB4EZkXx357IR:-LTx3kow7xkfDzU3iBNb:b41ah80) ([raw file](https://github.com/robotlocomotion/styleguide/blob/fa8a90e41994515caad2cd56bed93b4126db7872/cppguide.html#L3452)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW :smile:  I guess someone objected!
</blockquote></details>

OK Aww, I like `0.`...


<!-- Sent from Reviewable.io -->

2018-12-17 17:57 UTC, jwnimmer-tri approved these changes
I'll repost for the new folks: FYI a formatted preview is available [here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/EricCousineau-TRI/styleguide/update-gh-pages-20181213/cppguide.html).

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTxIxGL5ZBeh5D2XuZc:b-9t5288)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri], commit history needs curation



<!-- Sent from Reviewable.io -->

2018-12-17 18:00 UTC, ggould-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTx8tefDwJWiA2NDJD0:bnfp4nl)* status: 6 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri], commit history needs curation

___
*[cppguide.html, line 1104 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHTaSAbQctC_A508Q:-LTxHTaSAbQctC_A508R:b-nkmzv7) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1104)):*
> ```HTML
> 
> <div class="summary">
> <p><code>thread_local</code> variables that aren't declared inside a function
> ```

minor:  Consider `nondrake`ing this absl-specific `<p>` block.
___
*[cppguide.html, line 1180 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHi4S8dwSve5UMVtU:-LTxHi4T6y-LEHjvfC6D:b-nkmzv7) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1180)):*
> ```HTML
> </pre>
> 
>   <p><code>thread_local</code> variables at class or namespace scope must be
> ```

minor:  Consider `nondrake`ing this absl-specific `<p>` block.
___
*[cppguide.html, line 1261 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHnvS5sWBgzjSSBJS:-LTxHnvS5sWBgzjSSBJT:bow97hl) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1261)):*
> ```HTML
> ,
> terminating the program may be an appropriate error handling
> response. Otherwise, consider a factory function
> ```

minor:  Consider `nondrake`ing this absl-specific sentence.
___
*[cppguide.html, line 1399 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHxDD1o5X25iWAfPH:-LTxHxDD1o5X25iWAfPI:b-kiw46h) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1399)):*
> ```HTML
> <div class="summary">
> <p>A class's public API should make explicit whether the class is copyable,
> move-only, or neither copyable nor movable. Support copying and/or
> ```

minor:  Should we make explicit that the drake `*COPY*MOVE*ASSIGN` macros satisfy this requirement?
___
*[cppguide.html, line 2784 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxImN2-QxTzdm9tH5h:-LTxImN2-QxTzdm9tH5i:bdlujl) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L2784)):*
> ```HTML
> </div> 
> 
> <h3 id="noexcept"><code>noexcept</code></h3>
> ```

minor:  Do we wish to accept this standard?  It seems to imply a fairly universal change, insofar as most of our code is noexcept.
___
*[cppguide.html, line 6133 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxJnjq08ZSS2lM1VCP:-LTxJnjq08ZSS2lM1VCQ:b-olxsrc) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L6133)):*
> ```HTML
> </div> 
> 
> <p>Fall-through from one case label to
> ```

minor:  Consider `nondrake`ing this absl-specific `<p>` block amd the `<div>` that follows


<!-- Sent from Reviewable.io -->

2018-12-17 18:09 UTC, jwnimmer-tri approved these changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 6 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri], commit history needs curation

___
*[cppguide.html, line 2784 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxImN2-QxTzdm9tH5h:-LTxLYDu4MegYI1VzppR:bvw33ql) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L2784)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Do we wish to accept this standard?  It seems to imply a fairly universal change, insofar as most of our code is noexcept.
</blockquote></details>

I think this rule is good.  The immediately-below sentence isn't a great exposition, but if you read the full details its basically boils down to "mark your move ctors noexcept; if you want to mark something else also for performance, as your project lead".  Basically the bar for "useful and correct" is pretty high.


<!-- Sent from Reviewable.io -->

2018-12-17 18:17 UTC, ggould-tri approved these changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 5 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri], commit history needs curation

___
*[cppguide.html, line 2784 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxImN2-QxTzdm9tH5h:-LTxNR-w8UrEkXCq29nl:b-2fhg4r) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L2784)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I think this rule is good.  The immediately-below sentence isn't a great exposition, but if you read the full details its basically boils down to "mark your move ctors noexcept; if you want to mark something else also for performance, as your project lead".  Basically the bar for "useful and correct" is pretty high.
</blockquote></details>

Works for me.

(I'd be happy decking the halls with noexcept garlands throughout, mostly I just wanted to be sure we were opting into this change rather than stumbling into it)


<!-- Sent from Reviewable.io -->

2018-12-17 18:26 UTC, sherm1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTxPiKIC-ONknYMZ8Rq:bnfp4nl)* status: 5 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri, sherm1], commit history needs curation



<!-- Sent from Reviewable.io -->

2018-12-17 18:37 UTC, SeanCurtis-TRI approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> skipping most of the other languages.

> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTxSDxTDRUSWp4FuS1F:b-ludopu)* status: 7 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri, sherm1, seancurtis-tri], commit history needs curation

___
*[cppguide.html, line 1486 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxMHuN598YAu7wSk__:-LTxMHuN598YAu7wSk_a:b-s4edsh) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1486)):*
> ```HTML
> macros (either <code>DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN</code> or
> <code>DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN</code>) whenever practical.
> Failing that, it</span> should usually take the form of explicitly
> ```

nit: the closed span is in the wrong place? Seems odd to terminate the drake-specific documentation mid-sentence. And if it were simply excised, the remaining text wouldn't be grammatical.
___
*[cppguide.html, line 1500 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxMpGP3yX8Lgl6lADj:-LTxMpGP3yX8Lgl6lADk:b-w9bttc) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1500)):*
> ```HTML
> <pre>
> <span class="nondrake">class Copyable {
>  public:
> ```

BTW The deletion of this example and the absence of a `copy-only` macro implies that Drake disallows this. We should either be explicit about this or consider this a defect in our set of macros.

In contrast, the `MoveOnly` example below accounts for all four (which we *do* require) so it might make sense to mirror that.
___
*[cppguide.html, line 1518 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxNDKoBkrTZBw7nrAw:-LTxNDKoBkrTZBw7nrAx:b-dvavu6) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1518)):*
> ```HTML
> 
>   // The copy operations are implicitly deleted, but you can
>   // spell that out explicitly if you want:
> ```

BTW Is it a Drake-ism to say "but you can spell that out explicitly if you want"?
___
*[cppguide.html, line 3149 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxPPTp4UxGFTKnGMNw:-LTxPPTp4UxGFTKnGMNx:b-nq1nwy) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L3149)):*
> ```HTML
> 
> <p class="drake">Use
> <a href="https://github.com/RobotLocomotion/drake/blob/master/common/text_logging.h"><code>drake/common/text_logging.h</code></a> when possible.
> ```

nit: A part of my soul is desperate for a closing `</p>` here. Although the original style guide is somewhat erratic in this regard.
___
*[cppguide.html, line 4969 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxQteq152fXa-tYHYN:-LTxQteq152fXa-tYHYO:b-24x664) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L4969)):*
> ```HTML
> <p>You're not really going to <a href="#Preprocessor_Macros">
> define a macro</a>, are you? If you do, they're like this:
> <code>MY_MACRO_THAT_SCARES_SMALL_CHILDREN_AND_ADULTS_ALIKE</code>.
> ```

BTW Hands down my favorite upgrade.
___
*[cppguide.html, line 5646 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxR9M78AVcpuSa74EM:-LTxR9M78AVcpuSa74EN:b-q6dwpw) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L5646)):*
> ```HTML
>   <li>a <a href="#The__define_Guard">header guard</a></li>
> 
>   <li>a using-declaration</li>
> ```

BTW Is our cpplint up to date w.r.t. all of this?


<!-- Sent from Reviewable.io -->

2018-12-17 18:43 UTC, jwnimmer-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: 7 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri, sherm1, seancurtis-tri], commit history needs curation

___
*[cppguide.html, line 5646 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxR9M78AVcpuSa74EM:-LTxT7z_3huh251NEkvw:b-izv68q) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L5646)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Is our cpplint up to date w.r.t. all of this?
</blockquote></details>

It is possible that for some kinds of long lines that this list explicitly allows we'd need to add a NOLINTNEXTLINE directive immediately above it to silence cpplint.  I'm okay with that.


<!-- Sent from Reviewable.io -->

2018-12-17 18:56 UTC, sammy-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> for the C++ bits 

> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTxWZ-UASQkjsirVHcg:b-rnu988)* status: 6 unresolved discussions, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri, sherm1, seancurtis-tri, sammy-tri], commit history needs curation



<!-- Sent from Reviewable.io -->

2018-12-18 00:59 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: all discussions resolved, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri, sherm1, seancurtis-tri, sammy-tri], commit history needs curation

___
*[cppguide.html, line 1104 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHTaSAbQctC_A508Q:-LTymFa02zHx-_BiaqWx:b-eg6vo) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1104)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider `nondrake`ing this absl-specific `<p>` block.
</blockquote></details>

OK Per above discussion and disclaimer at the top, will keep as-is.
___
*[cppguide.html, line 1180 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHi4S8dwSve5UMVtU:-LTykNb533hNuh7ZmpVD:bb3036a) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1180)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider `nondrake`ing this absl-specific `<p>` block.
</blockquote></details>

OK Per prior discussions and disclaimer at the top, will keep as-is.
___
*[cppguide.html, line 1261 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHnvS5sWBgzjSSBJS:-LTykN4-AyBJSbQEjVId:bb3036a) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1261)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider `nondrake`ing this absl-specific sentence.
</blockquote></details>

OK Per prior discussions and disclaimer at the top, will keep as-is.
___
*[cppguide.html, line 1399 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxHxDD1o5X25iWAfPH:-LTykIoN4uimqzSg8VRR:bb3036a) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L1399)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Should we make explicit that the drake `*COPY*MOVE*ASSIGN` macros satisfy this requirement?
</blockquote></details>

OK Per prior discussions and disclaimer at the top, will keep as-is.
___
*[cppguide.html, line 5646 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxR9M78AVcpuSa74EM:-LTylo_408PRMz1fCc5p:b-vp3vxr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L5646)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It is possible that for some kinds of long lines that this list explicitly allows we'd need to add a NOLINTNEXTLINE directive immediately above it to silence cpplint.  I'm okay with that.
</blockquote></details>

OK Agreed, we can do it case-by-case, and then update linting if it becomes a pain point.
___
*[cppguide.html, line 6133 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxJnjq08ZSS2lM1VCP:-LTylup14UdOuc-0cdYx:b-eg6vo) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L6133)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider `nondrake`ing this absl-specific `<p>` block amd the `<div>` that follows
</blockquote></details>

OK Per above discussion and disclaimer at the top, will keep as-is.


<!-- Sent from Reviewable.io -->

2018-12-18 01:02 UTC, EricCousineau-TRI reviewed
-@russtedrake per Slack convo to get the PR landed

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-:-LTyp2keE8oz66bDj7Jj:b-c1c6rj)* status: all discussions resolved, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri, sherm1, seancurtis-tri, sammy-tri]



<!-- Sent from Reviewable.io -->

2018-12-18 01:03 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/16)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, soonho-tri, ggould-tri, sherm1, seancurtis-tri, sammy-tri]

___
*[cppguide.html, line 4969 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/16#-LTxQteq152fXa-tYHYN:-LTyphDh7S5fmRCCWpp-:b-r07cmu) ([raw file](https://github.com/robotlocomotion/styleguide/blob/53e24910d8490de770145102a64118631c0a88b7/cppguide.html#L4969)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Hands down my favorite upgrade.
</blockquote></details>

OK Agreed!


<!-- Sent from Reviewable.io -->

2018-12-18 01:03 UTC, merged