Add a subsection "Pass by Value"
RobotLocomotion/styleguide pull request #17
Opened 2019-01-04 19:30 UTC by soonho-tri

You can check the rendered HTML at https://soonho-tri.github.io/styleguide/cppguide.html#Pass_By_Value.

2019-01-04 19:30 UTC, soonho-tri commented
+@jwnimmer-tri for feature-review, please.

2019-01-04 19:33 UTC, edrumwri requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

___
*[cppguide.html, line 4654 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPLnVY4ejtVesMIzNC:-LVPLnVY4ejtVesMIzND:b-6c2koe) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a0c3d8eff1f45100f8660173ac4d8bc83271bf55/cppguide.html#L4654)):*
> ```HTML
> <p>
> When <code>Foo f1{s}</code> is executed, the
> parameter <code>str</code> is <em>copy</em>-constructued from the
> ```

Typo: "constructued"


<!-- Sent from Reviewable.io -->

2019-01-04 19:35 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing

___
*[cppguide.html, line 4654 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPLnVY4ejtVesMIzNC:-LVPMFaS3LrqiI_6rgt3:b-ioxi27) ([raw file](https://github.com/robotlocomotion/styleguide/blob/a0c3d8eff1f45100f8660173ac4d8bc83271bf55/cppguide.html#L4654)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Typo: "constructued"
</blockquote></details>

Done. Thank you!


<!-- Sent from Reviewable.io -->

2019-01-04 19:41 UTC, soonho-tri commented
+@RussTedrake
+@EricCousineau-TRI
+@ggould-tri
+@sammy-tri
+@SeanCurtis-TRI
+@sherm1

2019-01-04 19:41 UTC, edrumwri reviewed
This page provides some nice info: https://stackoverflow.com/questions/10789740/passing-stdstring-by-value-or-reference

Specifically, this link is cited: http://cpp-next.com/archive/2009/08/want-speed-pass-by-value/. A key observation is that this mechanism should be considered when it's common to pass a temporary. I don't think that's reflected (explicitly anyway) in this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPMq8T4A_n7K6o7kPr:b2cpwp6)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing



<!-- Sent from Reviewable.io -->

2019-01-04 19:44 UTC, ggould-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee ericcousineau-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM missing

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPO8Nb1zetYKSuEaT0:-LVPO8Nc-0XcqqLmRv-8:byeyb2t) (no related file):*
This should have a class=drake marker.

---


<!-- Sent from Reviewable.io -->

2019-01-04 19:50 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee ericcousineau-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM missing

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPO8Nb1zetYKSuEaT0:-LVPPlXp9hn2H5UxTyDx:b-896fix) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

This should have a class=drake marker.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2019-01-04 19:57 UTC, ggould-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPRM1J4Sg6IR83YtKS:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee ericcousineau-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQuxm1MliUgihP6V-:-LVPQuxnE526x3ScfXje:b-ilq5gg) (no related file):*
minor:  Consider putting this section next to the "reference arguments" or "rvalue references" sections to which it relates more closely rather than at the end of the "other features" chapter?  Author's discretion.

---


<!-- Sent from Reviewable.io -->

2019-01-04 19:58 UTC, ggould-tri reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee ericcousineau-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri]



<!-- Sent from Reviewable.io -->

2019-01-04 20:05 UTC, EricCousineau-TRI requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> pending explicit scope to contrast against `const T&`, or expanding use cases to more general case.

BTW Couldn't open the `cpp-next` page; here's a Wayback link: (original went 404 after this date)
https://web.archive.org/web/20140205194657/cpp-next.com/archive/2009/08/want-speed-pass-by-value/

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPR26s-12FNCEwN54S:bkbre20)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQuxm1MliUgihP6V-:-LVPSCjUCesZPAMKp01o:b13btzl) (no related file):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  Consider putting this section next to the "reference arguments" or "rvalue references" sections to which it relates more closely rather than at the end of the "other features" chapter?  Author's discretion.
</blockquote></details>

If the focus of this snippet is to contrast pass-by-value against `const T&`, then I think it *should* belong in this section as a contrasting subsection.

However, if the focus is "pass-by-value" *in general*, then we should provide more info on using values, as Evan had pointed out.

(Raising to blocking)

---
___
*[cppguide.html, line 4613 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQruUEFQgY2-bsv2_:-LVPQruVDSTpYYQ3op6z:b95tjiy) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4613)):*
> ```HTML
> </p>
> 
> <p>Consider the following example to understand why this can be useful.</p>
> ```

nit Could this be rewritten to "As an example:"  ?
(other text here uses "For example:" and other explicit intros using colons ":")
___
*[cppguide.html, line 4636 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQPML-rIGJogD-dbI:-LVPQPML-rIGJogD-dbJ:bxtk1mp) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4636)):*
> ```HTML
> of <code>std::string</code>
> in <code>Foo::Foo</code>. The <code>Foo</code> class can be refactored
> by following the suggestion.
> ```

nit Could you change the final sentence to "The constructor can be refactored as:"  ?
___
*[cppguide.html, line 4643 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQG7m4P4rqjHcCyPQ:-LVPQG7m4P4rqjHcCyPR:b807p1l) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4643)):*
> ```HTML
> 
> class Foo() {
> public:
> ```

nit Other code snippets follow access specifier indentations; can you prefix `public` and `private` with a space?


<!-- Sent from Reviewable.io -->

2019-01-04 20:10 UTC, EricCousineau-TRI commented
*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQuxm1MliUgihP6V-:-LVPU-ju8VAz9BC9QQHB:btp9dfp) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

If the focus of this snippet is to contrast pass-by-value against `const T&`, then I think it *should* belong in this section as a contrasting subsection.

However, if the focus is "pass-by-value" *in general*, then we should provide more info on using values, as Evan had pointed out.

(Raising to blocking)
</blockquote></details>

(Perhaps it can be inserted as an exception in the `Reference Arguments` section, and reduce the amount of text by making a succinct permalink to a StackOverflow post, code snippet, or something of that sort?)

---


<!-- Sent from Reviewable.io -->

2019-01-04 20:33 UTC, sammy-tri requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 5 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri]

___
*[cppguide.html, line 4640 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPZD0h7qEg38A9A13T:-LVPZD0i-vtOv5RZGtgq:b-r9ojsr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4640)):*
> ```HTML
> 
> <pre>
> #include <utility> // for std::move
> ```

It doesn't look like the `<utility>` part of the line rendered correctly for me in the preview.


<!-- Sent from Reviewable.io -->

2019-01-04 20:51 UTC, SeanCurtis-TRI approved these changes
<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> I have a slight bias in favor of seeing this in the `Functions` section. But otherwise am content.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPcIVg3NiUGLvzTSJ3:b-77tkcs)* status: 5 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri]



<!-- Sent from Reviewable.io -->

2019-01-04 21:03 UTC, ggould-tri reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 5 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri]



<!-- Sent from Reviewable.io -->

2019-01-04 21:06 UTC, soonho-tri reviewed
@edrumwri 

I've added a "references section" which includes the "want speed pass by values" and S&O entry.

> A key observation is that this mechanism should be considered when it's common to pass a temporary. I don't think that's reflected (explicitly anyway) in this PR.

It's tricky since passing a temporary is not the only condition, it has to be stored into another location eventually (either copied or moved) and also should have a cheaper move-semantics. When I tried to summarize it, I realized that it's already well-summarized in the first sentence of this section: "Consider pass-by-value for copyable parameters that are cheap to move and always copied" which I took from the EC++11.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPdyD6CWfZVl4Tj6QC:bebox17)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQuxm1MliUgihP6V-:-LVPe_QV5TmENhOiXmE9:b-29f058) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(Perhaps it can be inserted as an exception in the `Reference Arguments` section, and reduce the amount of text by making a succinct permalink to a StackOverflow post, code snippet, or something of that sort?)
</blockquote></details>

@ericcousineau-tri : I believe that the focus is to contrast pass-by-value against const T&. Maybe we need to change the title of the section? I couldn't find a better one though.

@ericcousineau-tri, @ggould-tri, @seancurtis-tri : I moved it next to `Other C++ Features > Rvalue References" as "Other C++ Features > Pass by Value". Another option was put it as "Functions > Pass by Value" next to "Functions > Reference Arguments" but the current version reads better to me when I tried both.

---
___
*[cppguide.html, line 4613 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQruUEFQgY2-bsv2_:-LVPaGq4Al38zQg0SJHg:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4613)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Could this be rewritten to "As an example:"  ?
(other text here uses "For example:" and other explicit intros using colons ":")
</blockquote></details>

Done.
___
*[cppguide.html, line 4636 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQPML-rIGJogD-dbI:-LVPaHl80vofpir1Jj3T:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4636)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Could you change the final sentence to "The constructor can be refactored as:"  ?
</blockquote></details>

Done.
___
*[cppguide.html, line 4640 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPZD0h7qEg38A9A13T:-LVPaIXP3EWQ1dDDis0O:bhlgaas) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4640)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

It doesn't look like the `<utility>` part of the line rendered correctly for me in the preview.
</blockquote></details>

Done. (fixed)
___
*[cppguide.html, line 4643 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQG7m4P4rqjHcCyPQ:-LVPaJkyCvlY6LL-3sCo:b-at7hlq) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4643)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Other code snippets follow access specifier indentations; can you prefix `public` and `private` with a space?
</blockquote></details>

Done. (also changed indentations to be consistent with other code in the file)


<!-- Sent from Reviewable.io -->

2019-01-04 21:10 UTC, SeanCurtis-TRI approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 2 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri]



<!-- Sent from Reviewable.io -->

2019-01-04 21:35 UTC, sherm1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with a few suggested refinements to the text

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPmjUwDjRUU-jm2EIy:bbtk77e)* status: 4 unresolved discussions, LGTM missing from assignee sammy-tri, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1]

___
*[cppguide.html, line 4620 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPd8E9E6aTeAZA3fuF:-LVPd8E9E6aTeAZA3fuG:b-x5ptn1) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4620)):*
> ```HTML
> private:
>     std::string str_;
> };
> ```

nit code in GSG should follow GSG guidelines for indenting (2 spaces, etc)!
___
*[cppguide.html, line 4631 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPcARa2WC5pNAMe5Y_:-LVPcARa2WC5pNAMe5Ya:bsijno) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4631)):*
> ```HTML
> <p>
> The constructor of <code>Foo</code> takes a const reference
> of <code>std::string</code> which is <em>copied</em> into the class
> ```

BTW consider saying that the const reference parameter is bound to the temporary object returned by make_str(), then copied. My thought is that mentioning the temp object here makes it clearer that we can handle it better below.
___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVPe4JWAxnJX0KcVFXG:brcm13o) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
> ```HTML
> field <code>str_</code>.  When <code>Foo f2{make_str()}</code> is
> executed, the parameter <code>str</code> is <em>move</em>-constructed
> from the return value of <code>make_str()</code> (rvalue), then it
> ```

nit This first move is elided here. The str argument memory is used directly for the output of make_str(). (Not sure whether that's required but I tried it on both gcc and clang and each did only one move.)


<!-- Sent from Reviewable.io -->

2019-01-04 21:57 UTC, sammy-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPrhMZ-XtlrZRxaglw:bnfp4nl)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]



<!-- Sent from Reviewable.io -->

2019-01-04 21:57 UTC, sammy-tri approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]



<!-- Sent from Reviewable.io -->

2019-01-04 21:57 UTC, edrumwri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVPrpY-6hrZWw2VCDPj:bg7igkv)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]



<!-- Sent from Reviewable.io -->

2019-01-04 23:00 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

___
*[cppguide.html, line 4620 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPd8E9E6aTeAZA3fuF:-LVPuH0x2iBPmh2qIZqD:bv3uk1o) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4620)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit code in GSG should follow GSG guidelines for indenting (2 spaces, etc)!
</blockquote></details>

Done. (already fixed in the latest revision)
___
*[cppguide.html, line 4631 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPcARa2WC5pNAMe5Y_:-LVQ1-Ic-Ml4qvh-u6xo:bt4ox15) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4631)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider saying that the const reference parameter is bound to the temporary object returned by make_str(), then copied. My thought is that mentioning the temp object here makes it clearer that we can handle it better below.
</blockquote></details>

Done. Thanks for the suggestion!
___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVQ2JgHBbk_-XlCjHmb:bqs0xcm) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit This first move is elided here. The str argument memory is used directly for the output of make_str(). (Not sure whether that's required but I tried it on both gcc and clang and each did only one move.)
</blockquote></details>

OK. Good point, but I think it depends on the implementation of `make_str()` function and it is possible that the copy-elision does not happen (I've read https://docs.microsoft.com/en-us/previous-versions/ms364057(v=vs.80)#optimization-limitations). Could you check?


<!-- Sent from Reviewable.io -->

2019-01-04 23:00 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQuxm1MliUgihP6V-:-LVQ5GBlD3CFI3IIf0GH:b-896fix) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@ericcousineau-tri : I believe that the focus is to contrast pass-by-value against const T&. Maybe we need to change the title of the section? I couldn't find a better one though.

@ericcousineau-tri, @ggould-tri, @seancurtis-tri : I moved it next to `Other C++ Features > Rvalue References" as "Other C++ Features > Pass by Value". Another option was put it as "Functions > Pass by Value" next to "Functions > Reference Arguments" but the current version reads better to me when I tried both.


</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2019-01-04 23:18 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVQ99B-0DKW3mz1dF7n:b24uhli) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

OK. Good point, but I think it depends on the implementation of `make_str()` function and it is possible that the copy-elision does not happen (I've read https://docs.microsoft.com/en-us/previous-versions/ms364057(v=vs.80)#optimization-limitations). Could you check?
</blockquote></details>

Another reference: http://eel.is/c++draft/class.copy.elision#4


<!-- Sent from Reviewable.io -->

2019-01-04 23:57 UTC, sherm1 approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVQGOHZDpIEUiRKmL-o:b-egsb6k) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Another reference: http://eel.is/c++draft/class.copy.elision#4
</blockquote></details>

The Microsoft doc is old (2005). The eel.is doc was undated but could be current. [Here](https://en.cppreference.com/w/cpp/language/copy_elision) is a recent cppreference description. As I read it, at least in C++17, all copy and move elisions that _can_ be done, _must_ be done. I do see some caveats regarding re-thrown catch arguments but they don't seem relevant for the point you're making. I think in all the cases that matter to us, the move will get elided.


<!-- Sent from Reviewable.io -->

2019-01-05 00:03 UTC, EricCousineau-TRI requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

___
*[cppguide.html, line 2002 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVQJTQYC_JMromIn0B1:-LVQJTQZAHnohtonsNuZ:b-osw3lw) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b4483d13551057ad5c7a56665c0f57b4ebb713d5/cppguide.html#L2002)):*
> ```HTML
> <pre>void Foo(const string &amp;in, string *out);
> </pre>
> ```

Can you add a `drake`-specific note here, referencing the Pass By Value section?
___
*[cppguide.html, line 2620 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVQJ7uq4JBvB6ceSMzY:-LVQJ7uq4JBvB6ceSMzZ:b-q3x82t) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b4483d13551057ad5c7a56665c0f57b4ebb713d5/cppguide.html#L2620)):*
> ```HTML
> <p>
> "Consider pass-by-value for copyable parameters that are cheap to move and always copied"
> (Item 41 of Scott Meyers' <a href="http://shop.oreilly.com/product/0636920033707.do?cmp=af-code-books-video-product_cj_0636920033707_7708709">Effective Modern C++11</a>).
> ```

nit Can you explicitly state that this should happen instead of using a const lvalue reference? (It could be inferred from below, but would be nice to be explicit.)


<!-- Sent from Reviewable.io -->

2019-01-05 00:04 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPQuxm1MliUgihP6V-:-LVQJgbW0__nN9tKpY2d:b-y5ko8a) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK Commented below - calling it out at the top of the new section, and linking to this section from "Reference Arguments" would suffice for me!

---


<!-- Sent from Reviewable.io -->

2019-01-05 00:15 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVQKMu-1m6PZ7Kz_frT:-LVQKMu-1m6PZ7Kz_frU:b90ksoa) (no related file):*
From @ericcousineau-tri 's comment below:

> Can you explicitly state that this should happen instead of using a const lvalue reference? (It could be inferred from below, but would be nice to be explicit.)

So, the key question is "Should we mark it as a defect or not if we see `Foo::Foo(const std::string&)`?". In the current writing, my message is "this is a suggestion so please 'consider' using this idiom but it's not a defect even if you don't".

Do you think we need to enforce this more strictly? I think we need a consensus on that first.

---


<!-- Sent from Reviewable.io -->

2019-01-05 00:18 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVQKMu-1m6PZ7Kz_frT:-LVQMpKGAC8bCuaBYpw5:b6cvwxm) (no related file):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

From @ericcousineau-tri 's comment below:

> Can you explicitly state that this should happen instead of using a const lvalue reference? (It could be inferred from below, but would be nice to be explicit.)

So, the key question is "Should we mark it as a defect or not if we see `Foo::Foo(const std::string&)`?". In the current writing, my message is "this is a suggestion so please 'consider' using this idiom but it's not a defect even if you don't".

Do you think we need to enforce this more strictly? I think we need a consensus on that first.
</blockquote></details>

Ah, sorry! I overly-specified with the wrong wording...
I meant to ask if you could just contrast it explicitly, not demand it to the point of it being a defect.

---


<!-- Sent from Reviewable.io -->

2019-01-05 03:36 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVR1Hoh5A8LJqgwJ68N:b-kh6yhi) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

The Microsoft doc is old (2005). The eel.is doc was undated but could be current. [Here](https://en.cppreference.com/w/cpp/language/copy_elision) is a recent cppreference description. As I read it, at least in C++17, all copy and move elisions that _can_ be done, _must_ be done. I do see some caveats regarding re-thrown catch arguments but they don't seem relevant for the point you're making. I think in all the cases that matter to us, the move will get elided.
</blockquote></details>

Here is an example where NRVO is not applied. To demonstrate the case, I've added a user-defined class `Bar` and provided `make_bar` instead of using `std::string` and `make_str()`. 

```c++
#include <iostream>
#include <utility>

class Bar {
public:
  Bar() { std::cout << "Constructor of Bar.\n"; }
  Bar(const Bar&) { std::cout << "Copy-constructor of Bar.\n"; }
  Bar(Bar&&) { std::cout << "Move-constructor of Bar.\n"; }
};

Bar make_bar(int n) {
  Bar b1;  
  Bar b2;
  if (n > 0) {
    return b1;
  } else {
    return b2;
  }
}

class Foo {
public:
  Foo(Bar bar) : bar_{std::move(bar)} { }
private:
  Bar bar_;
};

int main() {
  Foo f{make_bar(3)};
}
```

The output from `clang-7.0.1` and `gcc-8.1.0` with `--std=c++17` is:
```
Constructor of Bar.
Constructor of Bar.
Move-constructor of Bar.
Move-constructor of Bar.
```
and it shows that there were two move-operations.

I admit that the example is pretty artificial. However, since we didn't constrain the implementation of `make_str` in this section, I think we should not exclude this behavior (no NRVO) in writing.


<!-- Sent from Reviewable.io -->

2019-01-05 06:08 UTC, sherm1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, LGTM missing from assignee russtedrake, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVRaUWf2hIeQvj4hstp:b-2qrlpb) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
There are two move constructions there but neither of them is the one you mentioned in the comment -- that one is still elided! Otherwise there would be three here. Because there are two possible sources (b1,b2) for the return value inside make_bar(), the result has to be moved into make_bar's return argument. But there is no move _from_ the return argument into the `bar` value parameter of Foo's constructor. The memory for that argument _is_ the return value for make_bar(). The second move is the one in Foo's constructor where bar gets moved to bar_.

The specific text I think should be changed is:
> When `Foo f2{make_str()}` is executed, the parameter `str` is 
_move_-constructed from the return value of `make_str()`...

That's the one that gets elided. It's not NRVO, just plain RVO I think.


<!-- Sent from Reviewable.io -->

2019-01-05 09:38 UTC, RussTedrake approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVSN1CNARWHvQWCAmPJ:bnfp4nl)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake]



<!-- Sent from Reviewable.io -->

2019-01-05 13:44 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVTDSBw3mbgzPNAzo49:b-tfh7x2) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
Now I understand. Thanks for the points!

Here are things that I learned today:

In C++14, compilers are permitted, but _not_ required to the optimization (RVO) here. For example, when I use `-fno-elide-constructors` compiler option (available in gcc/clang), I have three moves (instead of two).

In C++17, as you pointed out, compilers are _required_ to omit the move construction in this case. As a result, `-fno-elide-constructors` doesn't change the output (i.e. two moves).

I plan to make the following change, could you check? I try to avoid mentioning copy-elision due to the subtleties above (and it's not the focus of this section either).

Current:
> When Foo f2{make_str()} is executed, the parameter str is move-constructed from the returned rvalue of make_str(), then it is moved into the class field str_. Note that we replace a copy-construction with a move-construction which is cheaper for std::string. 

New:

When `Foo f2{make_str()}` is executed, the returned rvalue `make_str()` is _moved_ into the class field `str_`. Note that we replace a copy-construction with a move-construction which is cheaper for `std::string`. 


<!-- Sent from Reviewable.io -->

2019-01-05 16:32 UTC, SeanCurtis-TRI approved these changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVTqsUfCvl5EpZPldkf:bfr8ftq) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Now I understand. Thanks for the points!

Here are things that I learned today:

In C++14, compilers are permitted, but _not_ required to the optimization (RVO) here. For example, when I use `-fno-elide-constructors` compiler option (available in gcc/clang), I have three moves (instead of two).

In C++17, as you pointed out, compilers are _required_ to omit the move construction in this case. As a result, `-fno-elide-constructors` doesn't change the output (i.e. two moves).

I plan to make the following change, could you check? I try to avoid mentioning copy-elision due to the subtleties above (and it's not the focus of this section either).

Current:
> When Foo f2{make_str()} is executed, the parameter str is move-constructed from the returned rvalue of make_str(), then it is moved into the class field str_. Note that we replace a copy-construction with a move-construction which is cheaper for std::string. 

New:

When `Foo f2{make_str()}` is executed, the returned rvalue `make_str()` is _moved_ into the class field `str_`. Note that we replace a copy-construction with a move-construction which is cheaper for `std::string`. 

</blockquote></details>

I like the new text: principle over mechanism. Ultimately, it comes down to the fact that it's no worse than the always copy and sometimes can do a move instead.  :)


<!-- Sent from Reviewable.io -->

2019-01-05 21:17 UTC, sherm1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVUrdJi4K3OTdX7cUmg:b-mtgf3j) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I like the new text: principle over mechanism. Ultimately, it comes down to the fact that it's no worse than the always copy and sometimes can do a move instead.  :)
</blockquote></details>

I like the new text too -- thanks, Soonho! Also thanks for the experiment with c++14/17 -- I didn't know about -fno-elide-constructors and it is reassuring to see it behave the way the somewhat-hazy C++ documentation seems to imply.


<!-- Sent from Reviewable.io -->

2019-01-05 23:23 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake]

___
*[cppguide.html, line 4659 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVPe4JWAxnJX0KcVFXF:-LVVGPXrCylsK8bLMmRt:b-p0fa0a) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b9f4e213e0b20620a678b905dfcf601fbf8b77f7/cppguide.html#L4659)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I like the new text too -- thanks, Soonho! Also thanks for the experiment with c++14/17 -- I didn't know about -fno-elide-constructors and it is reassuring to see it behave the way the somewhat-hazy C++ documentation seems to imply.
</blockquote></details>

Done. Glad to know that you like the new version!
___
*[cppguide.html, line 2002 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVQJTQYC_JMromIn0B1:-LVVI6mJ5bXPL6I9z4tF:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b4483d13551057ad5c7a56665c0f57b4ebb713d5/cppguide.html#L2002)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can you add a `drake`-specific note here, referencing the Pass By Value section?
</blockquote></details>

Done.
___
*[cppguide.html, line 2620 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVQJ7uq4JBvB6ceSMzY:-LVVIneuDdW1OmBnl5a1:b-u3hysx) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b4483d13551057ad5c7a56665c0f57b4ebb713d5/cppguide.html#L2620)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you explicitly state that this should happen instead of using a const lvalue reference? (It could be inferred from below, but would be nice to be explicit.)
</blockquote></details>

Done. (Added text at the end. Also the first code is now using `badcode` tag which gives a visual contrast.)
![Screen Shot 2019-01-05 at 6.23.15 PM.png](https://files.reviewableusercontent.io/images/reviewable/20779767/6wFQ8ZDK7vfkSyfcJ9u5lfh6/Screen%20Shot%202019-01-05%20at%206.23.15%20PM.png)


<!-- Sent from Reviewable.io -->

2019-01-07 14:36 UTC, ggould-tri reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake]



<!-- Sent from Reviewable.io -->

2019-01-07 14:40 UTC, jwnimmer-tri approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-:-LVckSzk1QBVRTmGybU7:bnfp4nl)* status: 2 unresolved discussions, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake, jwnimmer-tri]

___
*[cppguide.html, line 2656 at r6](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVck3dq9GsZ99D2YfX6:-LVck3dq9GsZ99D2YfX7:boyjk83) ([raw file](https://github.com/robotlocomotion/styleguide/blob/49f2eb788bc858c5338ecec5132ad52e2930512a/cppguide.html#L2656)):*
> ```HTML
> 
> <pre>
> #include &lt;utility&gt; // for std::move
> ```

nit If developer wrote `// for std::move` in a header, we would defect it and make them remove it.  Thus, we shouldn't say here here (in a "good" example code section).

(I don't even think we need the `#include` at all -- nothing says that example snippets need to compile as a standalone TU.)


<!-- Sent from Reviewable.io -->

2019-01-07 14:56 UTC, EricCousineau-TRI approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: 1 unresolved discussion, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake, jwnimmer-tri]



<!-- Sent from Reviewable.io -->

2019-01-07 15:08 UTC, soonho-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake, jwnimmer-tri]

___
*[cppguide.html, line 2656 at r6](https://reviewable.io/reviews/robotlocomotion/styleguide/17#-LVck3dq9GsZ99D2YfX6:-LVcqZz70OoI38g3NBwO:b2ar3so) ([raw file](https://github.com/robotlocomotion/styleguide/blob/49f2eb788bc858c5338ecec5132ad52e2930512a/cppguide.html#L2656)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit If developer wrote `// for std::move` in a header, we would defect it and make them remove it.  Thus, we shouldn't say here here (in a "good" example code section).

(I don't even think we need the `#include` at all -- nothing says that example snippets need to compile as a standalone TU.)
</blockquote></details>

Done. (removed)


<!-- Sent from Reviewable.io -->

2019-01-07 15:09 UTC, jwnimmer-tri reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/17)* status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri, ericcousineau-tri, seancurtis-tri, sherm1, sammy-tri, russtedrake, jwnimmer-tri]



<!-- Sent from Reviewable.io -->

2019-01-07 15:36 UTC, merged