Add support for c++17 tuple destructuring (#487)
RobotLocomotion/styleguide pull request #22
Opened 2020-02-04 04:33 UTC by m-chaturvedi

Cherry-pick for https://github.com/google/styleguide/commit/26470f9ccb354ff2f6d098f831271a1833701b28 

Towards: https://github.com/RobotLocomotion/drake/issues/12577

---

C++17 adds support for tuple destructuring. This allow one to write
code such as:

```
std::pair<int, int> span = getSpan();
auto [start, end] = span;

// Use start as span.first and end as span.second
```

This makes cpplint recognize and allow a space before the '[' in this
situation.

This is a purposeful divergence from the internal version where the
entire whitespace/braces category was removed. It was decided to leave
the checks in since this is sometimes used without other formatting
tools.

Test: manual

2020-02-04 15:37 UTC, EricCousineau-TRI reviewed
+@ericcousineau-tri for review

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/22#-:-M-FqMJj9dpnrzRR6xCu:b7dr7wo)* status: all discussions resolved, LGTM missing from assignee ericcousineau-tri, platform LGTM missing (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2020-02-04 15:39 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/22)* status: 1 unresolved discussion, LGTM missing from assignee ericcousineau-tri, platform LGTM missing (waiting on @EricCousineau-TRI and @m-chaturvedi)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/22#-M-FqUTC6nt-pzFUGX1X:-M-FqUTC6nt-pzFUGX1Y:bmd7ili) (no related file):*
Before merging this, can you submit a Drake PR that updates to this SHA, and fixes the existing usages of `auto [start, end]`?

---


<!-- Sent from Reviewable.io -->

2020-02-04 15:39 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/22#-:-M-FqiqHEd8iRaFTerpi:bnfp4nl)* status: 1 unresolved discussion, platform LGTM from [ericcousineau-tri] (waiting on @EricCousineau-TRI and @m-chaturvedi)



<!-- Sent from Reviewable.io -->

2020-02-05 13:09 UTC, m-chaturvedi commented
https://github.com/RobotLocomotion/drake/pull/12687/files

2020-02-05 15:41 UTC, EricCousineau-TRI approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/22)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri]



<!-- Sent from Reviewable.io -->

2020-02-05 15:41 UTC, merged